#!/usr/bin/env python

import os
import feedparser
import smtplib
import transmissionrpc

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

with open('config', 'r') as f:
    #   Reads settings from a config file. Splits the line by ' ' character.
    #   If one argument is expected, it will pull second item. If one or more
    #   are expected, it will pull every item after the first into a list.
    lines = f.readlines()
    for line in lines:
        if 'quality' in line:
            line = line.strip().split(' ')
            quality = line[1]
        if 'feeds' in line:
            line = line.strip().split(' ')
            feedsFile = line[1]
        if 'targets' in line:
            line = line.strip().split(' ')
            targetsFile = line[1]
        if 'archive' in line:
            line = line.strip().split(' ')
            archiveFile = line[1]
        if 'fromaddr' in line:
            line = line.strip().split(' ')
            fromaddr = line[1]
        if 'toaddr' in line:
            line = line.strip().split(' ')
            toaddr = line[1:]
        if 'password' in line:
            line = line.strip().split(' ')
            password = line[1]
        if 'torrentdir' in line:
            line = line.strip().split(' ')
            torrentdir = line[1]


def startTorrent(link, directory):
    #   Connects to Transmission daemon and adds/starts the torrent.
    tc = transmissionrpc.Client('localhost', port=9091)
    tc.add_torrent(str(link), download_dir=str(directory))


def notifyMe(msg, subj, toaddr, fromaddr, password=password):
    #   Sends an e-mail from the 'fromaddr' e-mail to the 'toaddr'.
    message = MIMEMultipart()
    message['From'] = fromaddr
    message['To'] = toaddr
    message['Subject'] = subj
    message.attach(MIMEText(msg, 'plain'))
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login(fromaddr, password)
    text = message.as_string()
    server.sendmail(fromaddr, toaddr, text)


def addArchived(title):
    #   Writes 'title' variable to archive file, then a new line.
    with open(archiveFile, 'a') as stored:
        stored.write(title)
        stored.write('\n')


def checkArchived(title, archive):
    # Checks to see if the 'title' variable is in the archive file.
    if 'Batch' in title or 'batch' in title:
        return False
    for line in archive:
        if line == title:
            return False
    return True


def checkFolder(target):
    # Check if a directory exists for a given torrent, makes one if not.
    target = target.split(' ')
    target = ' '.join(target[1:])
    directory = f"{torrentdir}/{target}"
    if not os.path.isdir(directory):
        os.makedirs(directory)
    return directory


def whitespaceStrip(items):
    # Strips white space from a list.
    for index, item in enumerate(items):
        items[index] = item.strip()
    return items


def autoTorrent(feeds, targets, archive, quality):
    # Parses RSS feed by post, and compares 'targets' variable
    # to the title of the post, looking for a match. If there is
    # a match, it checks the archive file, ensuring it is not already in there.
    # It will then download the file to Transmission.
    for feed in feeds:
        currentFeed = feedparser.parse(feed)
        for post in currentFeed.entries:
            for target in targets:
                if target in post.title and str(quality) in post.title:
                    if checkArchived(post.title, archive):
                        directory = checkFolder(target)
                        startTorrent(post.link, directory)
                        addArchived(post.title)
                        subj = f"{post.title} has been downloaded"
                        msg = (f"{post.title} has been downloaded and stored"
                               f" in {directory}")
                        for email in toaddr:
                            notifyMe(msg, subj, email, fromaddr)


# Grab list of items you're looking for in the RSS feed, as well as the
# list of feeds to parse.
feeds = open(feedsFile, 'r').readlines()
targets = open(targetsFile, 'r').readlines()
archive = open(archiveFile, 'r').readlines()
quality = str(quality)

# Strip whitespace from config
feeds = whitespaceStrip(feeds)
targets = whitespaceStrip(targets)
archive = whitespaceStrip(archive)

autoTorrent(feeds, targets, archive, quality)
